language: php

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist
  - composer config --list --global
  - php artisan passport:install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ./vendor/bin/phpunit
